<?php declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class PopulateCountryTable extends AbstractMigration
{
    public function down(): void
    {
        $this->execute('DELETE FROM country');
    }

    public function up(): void
    {
        $formattedDate = (new \DateTime())->format('Y-m-d H:i:s');

        // Populate country table with ISO 3166-1 country codes
        // This data is required for movie_production_countries foreign key constraint
        $this->execute(
            <<<SQL
            INSERT INTO country (iso_3166_1, english_name, created_at) VALUES
            ('AD', 'Andorra', '$formattedDate'),
            ('AE', 'United Arab Emirates', '$formattedDate'),
            ('AF', 'Afghanistan', '$formattedDate'),
            ('AG', 'Antigua and Barbuda', '$formattedDate'),
            ('AI', 'Anguilla', '$formattedDate'),
            ('AL', 'Albania', '$formattedDate'),
            ('AM', 'Armenia', '$formattedDate'),
            ('AN', 'Netherlands Antilles', '$formattedDate'),
            ('AO', 'Angola', '$formattedDate'),
            ('AQ', 'Antarctica', '$formattedDate'),
            ('AR', 'Argentina', '$formattedDate'),
            ('AS', 'American Samoa', '$formattedDate'),
            ('AT', 'Austria', '$formattedDate'),
            ('AU', 'Australia', '$formattedDate'),
            ('AW', 'Aruba', '$formattedDate'),
            ('AZ', 'Azerbaijan', '$formattedDate'),
            ('BA', 'Bosnia and Herzegovina', '$formattedDate'),
            ('BB', 'Barbados', '$formattedDate'),
            ('BD', 'Bangladesh', '$formattedDate'),
            ('BE', 'Belgium', '$formattedDate'),
            ('BF', 'Burkina Faso', '$formattedDate'),
            ('BG', 'Bulgaria', '$formattedDate'),
            ('BH', 'Bahrain', '$formattedDate'),
            ('BI', 'Burundi', '$formattedDate'),
            ('BJ', 'Benin', '$formattedDate'),
            ('BM', 'Bermuda', '$formattedDate'),
            ('BN', 'Brunei Darussalam', '$formattedDate'),
            ('BO', 'Bolivia', '$formattedDate'),
            ('BR', 'Brazil', '$formattedDate'),
            ('BS', 'Bahamas', '$formattedDate'),
            ('BT', 'Bhutan', '$formattedDate'),
            ('BU', 'Burma', '$formattedDate'),
            ('BV', 'Bouvet Island', '$formattedDate'),
            ('BW', 'Botswana', '$formattedDate'),
            ('BY', 'Belarus', '$formattedDate'),
            ('BZ', 'Belize', '$formattedDate'),
            ('CA', 'Canada', '$formattedDate'),
            ('CC', 'Cocos  Islands', '$formattedDate'),
            ('CD', 'Congo', '$formattedDate'),
            ('CF', 'Central African Republic', '$formattedDate'),
            ('CG', 'Congo', '$formattedDate'),
            ('CH', 'Switzerland', '$formattedDate'),
            ('CI', 'Cote D\'Ivoire', '$formattedDate'),
            ('CK', 'Cook Islands', '$formattedDate'),
            ('CL', 'Chile', '$formattedDate'),
            ('CM', 'Cameroon', '$formattedDate'),
            ('CN', 'China', '$formattedDate'),
            ('CO', 'Colombia', '$formattedDate'),
            ('CR', 'Costa Rica', '$formattedDate'),
            ('CS', 'Serbia and Montenegro', '$formattedDate'),
            ('CU', 'Cuba', '$formattedDate'),
            ('CV', 'Cape Verde', '$formattedDate'),
            ('CX', 'Christmas Island', '$formattedDate'),
            ('CY', 'Cyprus', '$formattedDate'),
            ('CZ', 'Czech Republic', '$formattedDate'),
            ('DE', 'Germany', '$formattedDate'),
            ('DJ', 'Djibouti', '$formattedDate'),
            ('DK', 'Denmark', '$formattedDate'),
            ('DM', 'Dominica', '$formattedDate'),
            ('DO', 'Dominican Republic', '$formattedDate'),
            ('DZ', 'Algeria', '$formattedDate'),
            ('EC', 'Ecuador', '$formattedDate'),
            ('EE', 'Estonia', '$formattedDate'),
            ('EG', 'Egypt', '$formattedDate'),
            ('EH', 'Western Sahara', '$formattedDate'),
            ('ER', 'Eritrea', '$formattedDate'),
            ('ES', 'Spain', '$formattedDate'),
            ('ET', 'Ethiopia', '$formattedDate'),
            ('FI', 'Finland', '$formattedDate'),
            ('FJ', 'Fiji', '$formattedDate'),
            ('FK', 'Falkland Islands', '$formattedDate'),
            ('FM', 'Micronesia', '$formattedDate'),
            ('FO', 'Faeroe Islands', '$formattedDate'),
            ('FR', 'France', '$formattedDate'),
            ('GA', 'Gabon', '$formattedDate'),
            ('GB', 'United Kingdom', '$formattedDate'),
            ('GD', 'Grenada', '$formattedDate'),
            ('GE', 'Georgia', '$formattedDate'),
            ('GF', 'French Guiana', '$formattedDate'),
            ('GH', 'Ghana', '$formattedDate'),
            ('GI', 'Gibraltar', '$formattedDate'),
            ('GL', 'Greenland', '$formattedDate'),
            ('GM', 'Gambia', '$formattedDate'),
            ('GN', 'Guinea', '$formattedDate'),
            ('GP', 'Guadaloupe', '$formattedDate'),
            ('GQ', 'Equatorial Guinea', '$formattedDate'),
            ('GR', 'Greece', '$formattedDate'),
            ('GS', 'South Georgia and the South Sandwich Islands', '$formattedDate'),
            ('GT', 'Guatemala', '$formattedDate'),
            ('GU', 'Guam', '$formattedDate'),
            ('GW', 'Guinea-Bissau', '$formattedDate'),
            ('GY', 'Guyana', '$formattedDate'),
            ('HK', 'Hong Kong', '$formattedDate'),
            ('HM', 'Heard and McDonald Islands', '$formattedDate'),
            ('HN', 'Honduras', '$formattedDate'),
            ('HR', 'Croatia', '$formattedDate'),
            ('HT', 'Haiti', '$formattedDate'),
            ('HU', 'Hungary', '$formattedDate'),
            ('ID', 'Indonesia', '$formattedDate'),
            ('IE', 'Ireland', '$formattedDate'),
            ('IL', 'Israel', '$formattedDate'),
            ('IN', 'India', '$formattedDate'),
            ('IO', 'British Indian Ocean Territory', '$formattedDate'),
            ('IQ', 'Iraq', '$formattedDate'),
            ('IR', 'Iran', '$formattedDate'),
            ('IS', 'Iceland', '$formattedDate'),
            ('IT', 'Italy', '$formattedDate'),
            ('JM', 'Jamaica', '$formattedDate'),
            ('JO', 'Jordan', '$formattedDate'),
            ('JP', 'Japan', '$formattedDate'),
            ('KE', 'Kenya', '$formattedDate'),
            ('KG', 'Kyrgyz Republic', '$formattedDate'),
            ('KH', 'Cambodia', '$formattedDate'),
            ('KI', 'Kiribati', '$formattedDate'),
            ('KM', 'Comoros', '$formattedDate'),
            ('KN', 'St. Kitts and Nevis', '$formattedDate'),
            ('KP', 'North Korea', '$formattedDate'),
            ('KR', 'South Korea', '$formattedDate'),
            ('KW', 'Kuwait', '$formattedDate'),
            ('KY', 'Cayman Islands', '$formattedDate'),
            ('KZ', 'Kazakhstan', '$formattedDate'),
            ('LA', 'Lao People\'s Democratic Republic', '$formattedDate'),
            ('LB', 'Lebanon', '$formattedDate'),
            ('LC', 'St. Lucia', '$formattedDate'),
            ('LI', 'Liechtenstein', '$formattedDate'),
            ('LK', 'Sri Lanka', '$formattedDate'),
            ('LR', 'Liberia', '$formattedDate'),
            ('LS', 'Lesotho', '$formattedDate'),
            ('LT', 'Lithuania', '$formattedDate'),
            ('LU', 'Luxembourg', '$formattedDate'),
            ('LV', 'Latvia', '$formattedDate'),
            ('LY', 'Libyan Arab Jamahiriya', '$formattedDate'),
            ('MA', 'Morocco', '$formattedDate'),
            ('MC', 'Monaco', '$formattedDate'),
            ('MD', 'Moldova', '$formattedDate'),
            ('ME', 'Montenegro', '$formattedDate'),
            ('MG', 'Madagascar', '$formattedDate'),
            ('MH', 'Marshall Islands', '$formattedDate'),
            ('MK', 'Macedonia', '$formattedDate'),
            ('ML', 'Mali', '$formattedDate'),
            ('MM', 'Myanmar', '$formattedDate'),
            ('MN', 'Mongolia', '$formattedDate'),
            ('MO', 'Macao', '$formattedDate'),
            ('MP', 'Northern Mariana Islands', '$formattedDate'),
            ('MQ', 'Martinique', '$formattedDate'),
            ('MR', 'Mauritania', '$formattedDate'),
            ('MS', 'Montserrat', '$formattedDate'),
            ('MT', 'Malta', '$formattedDate'),
            ('MU', 'Mauritius', '$formattedDate'),
            ('MV', 'Maldives', '$formattedDate'),
            ('MW', 'Malawi', '$formattedDate'),
            ('MX', 'Mexico', '$formattedDate'),
            ('MY', 'Malaysia', '$formattedDate'),
            ('MZ', 'Mozambique', '$formattedDate'),
            ('NA', 'Namibia', '$formattedDate'),
            ('NC', 'New Caledonia', '$formattedDate'),
            ('NE', 'Niger', '$formattedDate'),
            ('NF', 'Norfolk Island', '$formattedDate'),
            ('NG', 'Nigeria', '$formattedDate'),
            ('NI', 'Nicaragua', '$formattedDate'),
            ('NL', 'Netherlands', '$formattedDate'),
            ('NO', 'Norway', '$formattedDate'),
            ('NP', 'Nepal', '$formattedDate'),
            ('NR', 'Nauru', '$formattedDate'),
            ('NU', 'Niue', '$formattedDate'),
            ('NZ', 'New Zealand', '$formattedDate'),
            ('OM', 'Oman', '$formattedDate'),
            ('PA', 'Panama', '$formattedDate'),
            ('PE', 'Peru', '$formattedDate'),
            ('PF', 'French Polynesia', '$formattedDate'),
            ('PG', 'Papua New Guinea', '$formattedDate'),
            ('PH', 'Philippines', '$formattedDate'),
            ('PK', 'Pakistan', '$formattedDate'),
            ('PL', 'Poland', '$formattedDate'),
            ('PM', 'St. Pierre and Miquelon', '$formattedDate'),
            ('PN', 'Pitcairn Island', '$formattedDate'),
            ('PR', 'Puerto Rico', '$formattedDate'),
            ('PS', 'Palestinian Territory', '$formattedDate'),
            ('PT', 'Portugal', '$formattedDate'),
            ('PW', 'Palau', '$formattedDate'),
            ('PY', 'Paraguay', '$formattedDate'),
            ('QA', 'Qatar', '$formattedDate'),
            ('RE', 'Reunion', '$formattedDate'),
            ('RO', 'Romania', '$formattedDate'),
            ('RS', 'Serbia', '$formattedDate'),
            ('RU', 'Russia', '$formattedDate'),
            ('RW', 'Rwanda', '$formattedDate'),
            ('SA', 'Saudi Arabia', '$formattedDate'),
            ('SB', 'Solomon Islands', '$formattedDate'),
            ('SC', 'Seychelles', '$formattedDate'),
            ('SD', 'Sudan', '$formattedDate'),
            ('SE', 'Sweden', '$formattedDate'),
            ('SG', 'Singapore', '$formattedDate'),
            ('SH', 'St. Helena', '$formattedDate'),
            ('SI', 'Slovenia', '$formattedDate'),
            ('SJ', 'Svalbard & Jan Mayen Islands', '$formattedDate'),
            ('SK', 'Slovakia', '$formattedDate'),
            ('SL', 'Sierra Leone', '$formattedDate'),
            ('SM', 'San Marino', '$formattedDate'),
            ('SN', 'Senegal', '$formattedDate'),
            ('SO', 'Somalia', '$formattedDate'),
            ('SR', 'Suriname', '$formattedDate'),
            ('SS', 'South Sudan', '$formattedDate'),
            ('ST', 'Sao Tome and Principe', '$formattedDate'),
            ('SU', 'Soviet Union', '$formattedDate'),
            ('SV', 'El Salvador', '$formattedDate'),
            ('SY', 'Syrian Arab Republic', '$formattedDate'),
            ('SZ', 'Swaziland', '$formattedDate'),
            ('TC', 'Turks and Caicos Islands', '$formattedDate'),
            ('TD', 'Chad', '$formattedDate'),
            ('TF', 'French Southern Territories', '$formattedDate'),
            ('TG', 'Togo', '$formattedDate'),
            ('TH', 'Thailand', '$formattedDate'),
            ('TJ', 'Tajikistan', '$formattedDate'),
            ('TK', 'Tokelau', '$formattedDate'),
            ('TL', 'Timor-Leste', '$formattedDate'),
            ('TM', 'Turkmenistan', '$formattedDate'),
            ('TN', 'Tunisia', '$formattedDate'),
            ('TO', 'Tonga', '$formattedDate'),
            ('TP', 'East Timor', '$formattedDate'),
            ('TR', 'Turkey', '$formattedDate'),
            ('TT', 'Trinidad and Tobago', '$formattedDate'),
            ('TV', 'Tuvalu', '$formattedDate'),
            ('TW', 'Taiwan', '$formattedDate'),
            ('TZ', 'Tanzania', '$formattedDate'),
            ('UA', 'Ukraine', '$formattedDate'),
            ('UG', 'Uganda', '$formattedDate'),
            ('UM', 'United States Minor Outlying Islands', '$formattedDate'),
            ('US', 'United States of America', '$formattedDate'),
            ('UY', 'Uruguay', '$formattedDate'),
            ('UZ', 'Uzbekistan', '$formattedDate'),
            ('VA', 'Holy See', '$formattedDate'),
            ('VC', 'St. Vincent and the Grenadines', '$formattedDate'),
            ('VE', 'Venezuela', '$formattedDate'),
            ('VG', 'British Virgin Islands', '$formattedDate'),
            ('VI', 'US Virgin Islands', '$formattedDate'),
            ('VN', 'Vietnam', '$formattedDate'),
            ('VU', 'Vanuatu', '$formattedDate'),
            ('WF', 'Wallis and Futuna Islands', '$formattedDate'),
            ('WS', 'Samoa', '$formattedDate'),
            ('XC', 'Czechoslovakia', '$formattedDate'),
            ('XG', 'East Germany', '$formattedDate'),
            ('XI', 'Northern Ireland', '$formattedDate'),
            ('XK', 'Kosovo', '$formattedDate'),
            ('YE', 'Yemen', '$formattedDate'),
            ('YT', 'Mayotte', '$formattedDate'),
            ('YU', 'Yugoslavia', '$formattedDate'),
            ('ZA', 'South Africa', '$formattedDate'),
            ('ZM', 'Zambia', '$formattedDate'),
            ('ZR', 'Zaire', '$formattedDate'),
            ('ZW', 'Zimbabwe', '$formattedDate')
            SQL,
        );
    }
}
