<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class InitialSchema extends AbstractMigration
{
    public function up(): void
    {
        // This migration was auto-generated by consolidate-migrations.sh
        // It contains the complete database schema as of $(date +"%Y-%m-%d")

        $this->execute(file_get_contents(__DIR__ . '/../../schema_exports/mysql_schema.sql'));

        // Insert default locations (if not exists)
        $this->execute(<<<SQL
            INSERT INTO `location` (`name`, `user_id`, `created_at`)
            SELECT * FROM (
                SELECT 'Cinema' AS name, NULL AS user_id, NOW() AS created_at
                UNION ALL
                SELECT 'Home' AS name, NULL AS user_id, NOW() AS created_at
                UNION ALL
                SELECT 'Other' AS name, NULL AS user_id, NOW() AS created_at
            ) AS defaults
            WHERE NOT EXISTS (
                SELECT 1 FROM `location` WHERE `user_id` IS NULL
            )
        SQL);
    }

    public function down(): void
    {
        // Drop all tables
        $tables = [
            'watchlist',
            'user_trusted_devices',
            'user_security_audit_log',
            'user_recovery_codes',
            'user_person_settings',
            'user_jellyfin_cache',
            'user_invitation',
            'user_auth_token',
            'user_api_token',
            'user',
            'server_setting_metadata',
            'server_setting',
            'phinxlog',
            'person',
            'password_setup_attempts',
            'oauth_email_config',
            'oauth_admin_banner_ack',
            'movie_user_watch_dates',
            'movie_user_rating',
            'movie_production_countries',
            'movie_production_company',
            'movie_genre',
            'movie_crew',
            'movie_cast',
            'movie',
            'location',
            'job_queue',
            'genre',
            'email_send_log',
            'country',
            'company',
            'cache_trakt_user_movie_watched',
            'cache_trakt_user_movie_rating',
            'cache_tmdb_languages',
            'cache_letterboxd_diary',
        ];

        foreach ($tables as $table) {
            $this->execute("DROP TABLE IF EXISTS `{$table}`");
        }
    }
}
