#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}========================================${NC}"
echo -e "${YELLOW}Database Migration Consolidation Script${NC}"
echo -e "${YELLOW}========================================${NC}"
echo ""

# Step 1: Safety check
echo -e "${YELLOW}⚠️  WARNING: This script will:${NC}"
echo "  1. Archive all existing migrations to db/migrations_archive/"
echo "  2. Export current database schema"
echo "  3. Rename database from 'movary' to 'pathary'"
echo "  4. Create a new consolidated initial migration"
echo ""
echo -e "${RED}This should ONLY be run on a new project with no production installations!${NC}"
echo ""
read -p "Are you sure you want to continue? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo -e "${RED}Aborted.${NC}"
    exit 1
fi

# Step 2: Create archive directories
echo ""
echo -e "${GREEN}Creating archive directories...${NC}"
mkdir -p db/migrations_archive/mysql
mkdir -p db/migrations_archive/sqlite
mkdir -p db/schema_exports

# Step 3: Archive old migrations
echo -e "${GREEN}Archiving old migrations...${NC}"
if [ "$(ls -A db/migrations/mysql/*.php 2>/dev/null)" ]; then
    mv db/migrations/mysql/*.php db/migrations_archive/mysql/
    echo "  ✓ Archived $(ls db/migrations_archive/mysql/*.php | wc -l) MySQL migrations"
fi

if [ "$(ls -A db/migrations/sqlite/*.php 2>/dev/null)" ]; then
    mv db/migrations/sqlite/*.php db/migrations_archive/sqlite/
    echo "  ✓ Archived $(ls db/migrations_archive/sqlite/*.php | wc -l) SQLite migrations"
fi

# Step 4: Export current schema
echo ""
echo -e "${GREEN}Exporting current database schema...${NC}"

# MySQL schema export
echo "  → Exporting MySQL schema..."
docker compose exec -T mysql mysqldump -uroot -proot \
    --no-data \
    --skip-add-drop-table \
    --skip-comments \
    --skip-triggers \
    --skip-add-locks \
    --skip-disable-keys \
    movary 2>/dev/null > db/schema_exports/mysql_schema.sql

# Remove AUTO_INCREMENT values from export (they change on every export)
sed -i.bak 's/ AUTO_INCREMENT=[0-9]*//g' db/schema_exports/mysql_schema.sql
rm -f db/schema_exports/mysql_schema.sql.bak

echo "  ✓ MySQL schema exported to db/schema_exports/mysql_schema.sql"

# Step 4.5: Rename database from movary to pathary
echo ""
echo -e "${GREEN}Renaming database from 'movary' to 'pathary'...${NC}"

# Create pathary database
docker compose exec -T mysql mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS pathary CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;" 2>/dev/null

# Copy all tables from movary to pathary
docker compose exec -T mysql mysql -uroot -proot -e "
SET FOREIGN_KEY_CHECKS=0;
" 2>/dev/null

# Dump movary and restore to pathary
docker compose exec -T mysql mysqldump -uroot -proot movary 2>/dev/null | \
docker compose exec -T mysql mysql -uroot -proot pathary 2>/dev/null

echo "  ✓ Database renamed to 'pathary'"
echo "  ✓ Old 'movary' database preserved (can be dropped manually if needed)"

# Update schema export to use pathary
sed -i.bak 's/movary/pathary/g' db/schema_exports/mysql_schema.sql
rm -f db/schema_exports/mysql_schema.sql.bak

# Rename SQLite database files if they exist
echo ""
echo -e "${GREEN}Renaming SQLite database files...${NC}"

if [ -f "storage/movary.sqlite" ]; then
    mv storage/movary.sqlite storage/pathary.sqlite
    echo "  ✓ Renamed storage/movary.sqlite → storage/pathary.sqlite"
fi

if [ -f "db/movary.db" ]; then
    mv db/movary.db db/pathary.db
    echo "  ✓ Renamed db/movary.db → db/pathary.db"
fi

echo "  ✓ SQLite database files renamed"

# Step 5: Create new migration files
echo ""
echo -e "${GREEN}Creating new consolidated migration...${NC}"

# Generate timestamp for migration
TIMESTAMP=$(date +"%Y%m%d%H%M%S")

# Create MySQL migration file
cat > "db/migrations/mysql/${TIMESTAMP}_initial_schema.php" << 'EOF'
<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class InitialSchema extends AbstractMigration
{
    public function up(): void
    {
        // This migration was auto-generated by consolidate-migrations.sh
        // It contains the complete database schema as of $(date +"%Y-%m-%d")

        $this->execute(file_get_contents(__DIR__ . '/../../schema_exports/mysql_schema.sql'));

        // Insert default locations (if not exists)
        $this->execute(<<<SQL
            INSERT INTO `location` (`name`, `user_id`, `created_at`)
            SELECT * FROM (
                SELECT 'Cinema' AS name, NULL AS user_id, NOW() AS created_at
                UNION ALL
                SELECT 'Home' AS name, NULL AS user_id, NOW() AS created_at
                UNION ALL
                SELECT 'Other' AS name, NULL AS user_id, NOW() AS created_at
            ) AS defaults
            WHERE NOT EXISTS (
                SELECT 1 FROM `location` WHERE `user_id` IS NULL
            )
        SQL);
    }

    public function down(): void
    {
        // Drop all tables
        $tables = [
            'watchlist',
            'user_trusted_devices',
            'user_security_audit_log',
            'user_recovery_codes',
            'user_person_settings',
            'user_jellyfin_cache',
            'user_invitation',
            'user_auth_token',
            'user_api_token',
            'user',
            'server_setting_metadata',
            'server_setting',
            'phinxlog',
            'person',
            'password_setup_attempts',
            'oauth_email_config',
            'oauth_admin_banner_ack',
            'movie_user_watch_dates',
            'movie_user_rating',
            'movie_production_countries',
            'movie_production_company',
            'movie_genre',
            'movie_crew',
            'movie_cast',
            'movie',
            'location',
            'job_queue',
            'genre',
            'email_send_log',
            'country',
            'company',
            'cache_trakt_user_movie_watched',
            'cache_trakt_user_movie_rating',
            'cache_tmdb_languages',
            'cache_letterboxd_diary',
        ];

        foreach ($tables as $table) {
            $this->execute("DROP TABLE IF EXISTS `{$table}`");
        }
    }
}
EOF

echo "  ✓ Created db/migrations/mysql/${TIMESTAMP}_initial_schema.php"

# Create SQLite migration file (placeholder)
cat > "db/migrations/sqlite/${TIMESTAMP}_initial_schema.php" << 'EOF'
<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class InitialSchema extends AbstractMigration
{
    public function up(): void
    {
        // NOTE: This is a placeholder for SQLite migration
        // The SQLite schema should match the MySQL schema

        // For now, throw an error directing to manual setup
        throw new \RuntimeException(
            'SQLite initial schema not yet implemented. ' .
            'Please copy the table definitions from the MySQL migration ' .
            'and adapt them for SQLite syntax.'
        );
    }

    public function down(): void
    {
        // Drop all tables (implement if needed)
    }
}
EOF

echo "  ✓ Created db/migrations/sqlite/${TIMESTAMP}_initial_schema.php (placeholder)"

# Step 6: Summary
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Migration Consolidation Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "What was done:"
echo "  ✓ Archived old migrations to db/migrations_archive/"
echo "  ✓ Exported current schema to db/schema_exports/"
echo "  ✓ Created new consolidated migration"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo ""
echo "1. Review the new migration:"
echo "   cat db/migrations/mysql/${TIMESTAMP}_initial_schema.php"
echo ""
echo "2. Test on a fresh database:"
echo "   docker compose down -v"
echo "   docker volume rm pathary_mysql_data"
echo "   docker compose up -d"
echo "   make app_database_migrate"
echo ""
echo "3. If you're happy with the result:"
echo "   git add db/migrations/"
echo "   git add db/migrations_archive/"
echo "   git add db/schema_exports/"
echo "   git commit -m \"Consolidate database migrations into single initial schema\""
echo ""
echo -e "${YELLOW}⚠️  Note: The SQLite migration is a placeholder. You'll need to adapt it manually.${NC}"
echo ""
